openapi: 3.0.0
info:
  title: Capillary Promotions API
  version: 1.0.0
servers:
  - url: '{Host}'
    variables:
      Host:
        default: https://eu.intouch.capillarytech.com
        enum:
          - https://eu.intouch.capillarytech.com
          - https://intouch.capillary.co.in
          - https://apac2.intouch.capillarytech.com
          - https://sgcrm.cc.capillarytech.com
          - http://intouch.capillarytech.cn.com
          - https://north-america.intouch.capillarytech.com
paths:
  /api_gateway/v1/promotions/{promotionId}/deactivate:
    post:
      summary: Deactivate Promotion
      parameters:
        - name: promotionId
          in: path
          required: true
          schema:
            type: string
            example: 698ab5f73b42186a70163ddf
        - name: customerId
          in: query
          schema:
            type: string
            example: '566881933'
        - name: earnId
          in: query
          schema:
            type: string
            nullable: true
            example: 'null'
        - name: Authorization
          in: header
          schema:
            type: string
            default: Basic Z2VvcmdlLmRvY2RlbW86NjVhMDgzYjk1MWY5MGY1NTY5NDk1YmNkNzUxYm
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
